version: "2.4"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    networks:
     - lua-network
    ports:
      - 1883:1883
      - 9001:9001



  # client-rpc:
  #   image: brunoguic/lua:latest
  #   volumes:
  #     - "/home/brunoguic/masters/sd/trab2/src/:/src/"
  #   networks:
  #    - lua-network
  #   depends_on:
  #     - server-rpc
  #   command: ex5-client.lua ex5-interface.lua server-rpc 5500 5501
    
networks:
  lua-network:
    name: lua-network



# SERVER
# docker run \
#     --name server \
#     -v "/Users/bruno.castro/Development/lua-rpc/src/:/src/" \
#     --rm \
#     -p 5555:5555 \
#     -p 5556:5556 \
#     brunoguic/lua server.lua interface.lua

# CLIENT
# docker run \
#     --name client \
#     -v "/Users/bruno.castro/Development/lua-rpc/src/:/src/" \
#     --rm \
#     brunoguic/lua client.lua interface.lua 